version: "3"

services:
  mongodb:
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=opendatafit
      - MONGO_INITDB_ROOT_PASSWORD=password

  rabbitmq:
    ports:
      # AMQP port
      - "5672:5672"
      # Management UI port
      - "15672:15672"

  store:
    ports:
      - "5000:5000"
    env_file:
      - store.test.env

  users:
    ports:
      - "5001:5000"
    env_file:
      - users.test.env

  jobjockey:
    ports:
      - "5002:5000"
    env_file:
      - jobjockey.test.env

  scheduler:
    env_file:
      - scheduler.test.env

  execution:
    env_file:
      - execution.test.env
