version: "3"

services:
  mongodb:
    image: mongo:4.4.5-bionic
    volumes:
      - ./db-data:/data/db
    networks:
      - mongodb-network

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    networks:
      - rabbitmq-network

  store:
    image: opendatafit/store
    build:
      context: ${ODF_STORE_SRC}
    networks:
      - store-network
      - mongodb-network
    depends_on:
      - "mongodb"

  users:
    image: opendatafit/users
    build:
      context: ${ODF_USERS_SRC}
    networks:
      - mongodb-network
    depends_on:
      - "mongodb"

  jobjockey:
    image: opendatafit/jobjockey
    build:
      context: ${ODF_JOBJOCKEY_SRC}
    networks:
      - jobjockey-network  # Used by notify test-client
      - rabbitmq-network
    depends_on:
      - "rabbitmq"

  scheduler:
    image: opendatafit/scheduler
    build:
      context: ${ODF_SCHEDULER_SRC}
    networks:
      - rabbitmq-network
      - execution-network
    depends_on:
      - "rabbitmq"
      - "execution"

  execution:
    image: opendatafit/execution
    build:
      target: development
      context: ${ODF_EXECUTION_BASE_SRC}
    networks:
      - execution-network
      - store-network
    depends_on:
      - "store"

networks:
  mongodb-network:
    name: mongodb-network
  rabbitmq-network:
    name: rabbitmq-network
  jobjockey-network:
    name: jobjockey-network
  store-network:
    name: store-network
  execution-network:
    name: execution-network
